options:
  snap-channel:
    default: '2.6/stable'
    description: |
      Install ruby from snapstore
    type: string
  app-path:
    type: string
    default: '/srv/app'
    description: |
      The default location of your Ruby application, defaults /srv/app
