options:
  ruby-runtime:
    default: 'ruby'
    description: |
      Ruby implementation to install, ruby,jruby,rubinius,maglev,mruby are supported.
    type: string
  ruby-version:
    default: 'stable'
    description: |
      Ruby Version to use for your application, supported options are
      stable,latest,<version>. <version> is the version of ruby to install, for
      example, 2.4.2.
    type: string
